sudo: required

services:
  - docker

# We test against all influxdb versions with the most actual JDK.
# Test only the most recent influxdb version with JDK8 which will be legacy soon.
env:
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.5
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.4
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.3
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.2
  - MAVEN_JAVA_VERSION=3-jdk-10-slim INFLUXDB_VERSION=1.1
  - MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.5

script: ./compile-and-test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat target/surefire-reports/*.txt
