sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-utils

# We test against all influxdb versions with the most actual JDK.
# Test only the most recent influxdb version with JDK8 which will be legacy soon.
env:
  global:
  - secure: aCFuNNixYILZZfcOp0jI66om4w8Cbr+qtz1FUOVgbxeipFA93y7KLoXtFajkE1qmbHOdz8SvPcloY5q6HKIOYuqv4/6at+OaTogXELfrR+oKfxf2t5PfB1D+1RxM90+wjsEPGQh+HmFOEnGCnJ8ZUfcx76Afs+mPzbpjzKeNz7w=
  - secure: dAJK41xM2dN3q3xJMqAOP6uvrOvpjjUzmHr8mYNyepER8Lpms9/GqVUxqJv12wzCBqv1XZk/CXxrv3iBc2XjlxlrzIJGQChTinwDEigv0BMl/Gh0821ja7gwzMEUmg9f79m5tJxIFQ306cWz1gyRDqM3fLzskvM2ayzvynsNc/w=

  matrix:
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.8
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.7
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.6
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.5
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.4
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.3
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.2
  - MAVEN_JAVA_VERSION=3-jdk-14 INFLUXDB_VERSION=1.1
  - MAVEN_JAVA_VERSION=3-jdk-8-slim INFLUXDB_VERSION=1.8 SNAPSHOT=Y

script: "./compile-and-test.sh"

deploy:
  provider: script
  script: "./deploy-snapshot.sh"
  skip_cleanup: true
  on:
    repo: influxdata/influxdb-java
    condition: $SNAPSHOT == "Y" && $DEPLOY_SNAPSHOT == "Y"
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat target/surefire-reports/*.txt
